### PR TITLE
Adding Python 2.6 support, some cleanup

### PR DESCRIPTION
**Pull request by ghost**
I added in lib2to3 from Python 2.7.3 and modified some tests, the library now runs on Python 2.6. This doesn't increase the size of the lib too much, so I think it's an okay solution.

I also edited the tox.ini file to only check 2.6 and 2.7.

Most of the cleanup was in the setup.py file, simplifying it and adding some classifiers.

### CODE REVIEW

**Comment by myint** [comment]
Overwriting a built-in package seems a bit rude. (It will break other packages that depend on the usual `lib2to3`.) It would be better to vendorize `lib2to3` properly by putting it inside the `py3kwarn` package.

**Comment by liamcurry** [comment]
Great changes @dustinmm80! I merged your commits and removed all the 3.x versions of Python out of the travis config. I guess we should probably limit support to 2.6/2.7 only?

@myint good point. I was trying to move our copy of `lib2to3` into the `py3kwarn` package, but I've been running into problems:

``` bash
py3kwarn master ••• ⇒  ./setup.py test
running test
running egg_info
writing py3kwarn.egg-info/PKG-INFO
writing top-level names to py3kwarn.egg-info/top_level.txt
writing dependency_links to py3kwarn.egg-info/dependency_links.txt
reading manifest file 'py3kwarn.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'py3kwarn.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "./setup.py", line 40, in <module>
    test_suite='py3kwarn.tests')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/test.py", line 121, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/test.py", line 101, in with_project_on_sys_path
    func()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/test.py", line 130, in run_tests
    testLoader = loader_class()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/Users/cygni/Dropbox/Workspace/me/Programming/py3kwarn/py3kwarn/tests.py", line 5, in <module>
    from py3kwarn.run import warnings_for_string
  File "/Users/cygni/Dropbox/Workspace/me/Programming/py3kwarn/py3kwarn/run.py", line 113, in <module>
    _rt = WarnRefactoringTool(refactor.get_fixers_from_package('py3kwarn.lib2to3.fixes'))
  File "/Users/cygni/Dropbox/Workspace/me/Programming/py3kwarn/py3kwarn/lib2to3/refactor.py", line 221, in __init__
    self.BM.add_fixer(fixer)
  File "/Users/cygni/Dropbox/Workspace/me/Programming/py3kwarn/py3kwarn/lib2to3/btm_matcher.py", line 44, in add_fixer
    linear = tree.get_linear_subpattern()
AttributeError: 'NoneType' object has no attribute 'get_linear_subpattern'
```

I added you both as collaborators, so feel free to push any changes that you think add to the project.

**Comment by myint** [comment]
It looks like that is due to name collision. The system lib2to3 is getting picked up. I have a fix for that.

**Comment by liamcurry** [comment]
Nice! Feel free to push any changes/fixes you like.

**Comment by ghost** [comment]
@myint I agree about lib2to3, I've not had to do this before so I wasn't sure the best way to go about it. Vendorizing sounds good!

**Pull request merged**
